<?php

use Elogic\MyModule\Block\Widget\ReadMore;
/**
 *
 * @var ReadMore $block;
 */
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Elogic_MyModule/js/readMore": {
                "width": "<?= $block->getWidth() ?>"
            }
        }
    }
</script>
<div style="width: <?= $block->getWidth() ?>" id="readMore_wrapper" class="readmore_content_wrapper">
    <span id="readMore_text" class="readMore_text">
        <?= $block->getText() ?>
    </span>
    <div style="display: none" id="expand_text">
        <?= $block->getExpandText() ?>
    </div>
<div id="expand_button" class="expand_button">Read more</div>
</div>
